# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Psychologie - Bachelor (Universität Wien)
description: >- # this means to ignore newlines until "baseurl:"
  Notizen zu Lehrveranstaltungen des Bachelorstudiums Psychologie an der Universität Wien
baseurl: "/psy" # the subpath of your site, e.g. /blog
url: "http://blekdushi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: blekdushi
github_username: blekdushi

collections:
  ewd:
    output: true
    vo_name: Wissenschaftliches Denken
    steop: true
  pg:
    output: true
    vo_name: Paradigmengeschichte
    steop: true
  gf:
    output: true
    vo_name: Grundlagenfächer
    steop: true
  af:
    output: true
    vo_name: Anwendungsfelder
    steop: true
  KogEmo1:
    output: true
    vo_name: KogEmo 1
    vortragender: Leder
    semester: 2020W
    steop: false
  Diff1:
    output: true
    vo_name: Differentielle Psychologie 1
    vortragender: Pietschnig
    semester: 2020W
    steop: false

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

google_analytics: G-DXC1BFBDYF
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
