@startuml
skinparam activitybackgroundcolor white
skinparam activitybordercolor black
skinparam arrowcolor black
:Forschungsthema und -problem;
:**Forschungsstand und theoretischer Hintergrund**;
:Untersuchungsdesign;
:**Operationalisierung**;
:Stichprobe ziehen;
:Daten erheben;
:Daten aufbereiten;
:Daten analysieren;
:Ergebnisse präsentieren;
@enduml
