@startuml
hide circles
hide empty members

class "Forschungsthema und -problem" as 1
class "Forschungsstand und theoretischer Hintergrund" as 2
class "Untersuchungsdesign" as 3
package "" as a <<rectangle>> {
    class "Stichprobe ziehen" as 4
    class "Daten erheben" as 5
    class "Daten aufbereiten" as 6
    class "**Daten analysieren**" as 7
}
class "**Hypothesen und Theorien bilden**" as 8
class "Ergebnise präsentieren" as 9
1 --> 2
2 --> 3
3 <--> a
3 -[hidden]- 4
4 --> 5
5 --> 6
6 --> 7
7 -[hidden]- 8
a <--> 8
8 --> 9
@enduml
