@startuml
skinparam arrowcolor black
skinparam cardbackgroundcolor white

' Empirische Wissenschaften
card "Empirische Wissenschaften" as ew
card "Sozialwissenschaften" as sw
card swd [
     Psychologie
    ....
    Medizin
    ....
    Erziehungswiss.
    ....
    Soziologie
    ....
    Wirtschaftswiss.
    ....
    Kommunikationswiss.
    ....
    ...
]
card "Naturwissenschaften" as nw
card nwd [
     Physik
    ....
    Chemie
    ....
    Biologie
    ....
    Geowissenschaften
    ....
    Astronomie
    ....
    ...
]

card "Technikwissenschaften" as tw
card twd [
     Maschinenbau
    ....
    Elektrotechnik
    ....
    Bauningenieurwesen
    ....
    Informatik
    ....
    Verfahrenstechnik
    ....
    ...
]
ew -- sw
sw -- swd
ew -- nw
nw -- nwd
ew -- tw
tw -- twd

' nicht-empirische Wissenschaften
card "Nicht-empirische Wissenschaften" as new
card "Geisteswissenschaften" as gw
card gwd [
     Theologie
    ....
    Rechtswiss.
    ....
    Geschichte
    ....
    Literaturwiss.
    ....
    Sprachwiss.
    ....
    Medienwiss.
    ....
    ...
]
card "Formalwissenschaften" as fw
card fwd [
     Mathematik
    ....
    Philosophie
    ....
    ...
]
new -- gw
gw -- gwd
new -- fw
fw -- fwd

@enduml
